#!/bin/bash
#
# 
# nginx - this script starts and stops the nginx daemon 
# 
# chkconfig:   - 85 15 
# description:  Nginx is an HTTP(S) server, HTTP(S) reverse \ 
#               proxy and IMAP/POP3 proxy server 
# processname: nginx 

# @@@@@@@@@@@@@
# 更新记录

# 2015-07-30
  # + chkconfig 选项
  # + 导入 functions  

# @@@@@@@@@@@@@
#
# Source function library
[ -f /etc/init.d/functions ] && source /etc/init.d/functions

NGINX_PREFIX=$NGINX_PREFIX
[ -Z $NGINX_PREFIX ]  && { echo "Must need to Specify --> NGINX_PREFIX <-- directory " ; exit 1; } 
NGINX=$NGINX_PREFIX/sbin/nginx
NGINX_CONF=$NGINX_PREFIX/conf/nginx.conf
NGINX_PID=$NGINX_PREFIX/logs/nginx.pid 

NGINX_ACTION=$1

function status()
{
  if [ -f  $NGINX_PID ] 
  then
  {
    NGINX_PID_NUMBER=$(cat $NGINX_PID )
    echo "Nginx is Running at [ $NGINX_PID_NUMBER ] ! "
  }
  else 
  {
    echo "Nginx is stoped!"
  }
  fi
}

function start()
{
  $NGINX -c $NGINX_CONF
  status ;
}

function stop()
{
  $NGINX -s stop
  status;
}

function reload()
{
  $NGINX -s reload
  status;
}

function test()
{
  $NGINX -t $NGINX_CONF
}

function version()
{
  $NGINX -v
  ecoh ' '
  $NGINX -V
}


case $NGINX_ACTION in 
start|stop|test|reload|status|version)
  $NGINX_ACTION ;;
restart)
  stop && start ;;
*)
  echo "Usage: $0 [ start|stop|reload|restart|test|status|version ]"
  ;;
esac
