#!/bin/bash
#
# # nginx controller script
#
# # need to specify $NGINX_PREFIX
# 


NGINX_PREFIX=$NGINX_PREFIX
NGINX=$NGINX_PREFIX/sbin/nginx
NGINX_CONF=$NGINX_PREFIX/conf/nginx.conf
NGINX_PID=$NGINX_PREFIX/logs/nginx.pid 

NGINX_ACTION=$1

function status()
{
  if [ -f  $NGINX_PID ] 
  then
  {
    NGINX_PID_NUMBER=$(cat $NGINX_PID )
    echo "Nginx is Running at [ $NGINX_PID_NUMBER ] ! "
  }
  else 
  {
    echo "Nginx is stoped!"
  }
  fi
}

function start()
{
  $NGINX -c $NGINX_CONF
  status ;
}

function stop()
{
  $NGINX -s stop
  status;
}

function reload()
{
  $NGINX -s reload
  status;
}

function test()
{
  $NGINX -t $NGINX_CONF
}

function version()
{
  $NGINX -v
  ecoh ' '
  $NGINX -V
}


case $NGINX_ACTION in 
start|stop|test|reload|status|version)
  $NGINX_ACTION ;;
restart)
  stop && start ;;
*)
  echo "Usage: $0 [ start|stop|reload|restart|test|status|version ]"
  ;;
esac