#!/bin/bash
#
# # author: uyinn@live.com
# 
# # nginx controller script
# # need to specify $NGINX_PREFIX
# # download_url: https://raw.githubusercontent.com/uyinn/bash-scripts/master/nginx/nginxd

NGINX_PREFIX=$NGINX_PREFIX
[ -Z $NGINX_PREFIX ]  && { echo "Must need to Specify --> NGINX_PREFIX <-- directory " ; exit 1; } 
NGINX=$NGINX_PREFIX/sbin/nginx
NGINX_CONF=$NGINX_PREFIX/conf/nginx.conf
NGINX_PID=$NGINX_PREFIX/logs/nginx.pid 

NGINX_ACTION=$1

function status()
{
  if [ -f  $NGINX_PID ] 
  then
  {
    NGINX_PID_NUMBER=$(cat $NGINX_PID )
    echo "Nginx is Running [ $NGINX_PID_NUMBER ] ! "
  }
  else 
  {
    echo "Nginx is stoped!"
  }
  fi
  
  # 判断nginx进程是否存在
  # ps -ef |grep "nginx: master process" | egrep -v "grep|$0"
  
  # 思路：
  # 首先判断文件 nginx.pid 是否存在
  #   + 不存在, 判断 nginx 进程是否存在
  #     + 存在
}

function start()
{
  $NGINX -c $NGINX_CONF
  status ;
}

function stop()
{
  $NGINX -s stop
  status;
}

function reload()
{
  $NGINX -s reload
  status;
}

function test()
{
  $NGINX -t $NGINX_CONF
}

function version()
{
  $NGINX -v
  ecoh ' '
  $NGINX -V
}


case $NGINX_ACTION in 
start|stop|test|reload|status|version)
  $NGINX_ACTION ;;
restart)
  stop && start ;;
*)
  echo "Usage: $0 [ start|stop|reload|restart|test|status|version ]"
  ;;
esac
